# Generated by Django 5.0.4 on 2024-05-06 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SP_CaPhe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenSanPham', models.CharField(max_length=100)),
                ('Gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MoTa', models.TextField()),
                ('Anh', models.CharField(max_length=255)),
                ('LoaiSanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SP_CaPhe.loaisanpham')),
            ],
        ),
    ]
   