# Generated by Django 5.0.1 on 2024-05-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SP_CaPhe', '0005_alter_order_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='Suger_level',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
